export default {
  WELCOME_SCREEN: 'WelcomeScreen',
  ONBOARD_SCREEN: 'OnboardScreen',
  LOGIN_SCREEN: 'LoginScreen',
  CHATS_SCREEN: 'ChatsScreen',
  CHAT_SCREEN: 'ChatScreen',
  QUESTION_SCREEN: 'QuestionScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  DIARY_ENTRY_SCREEN: 'DiaryEntryScreen',
  DIARY_ENTRY_CHAT_SCREEN: 'DiaryEntryChatScreen',
  SEARCH_SCREEN: 'SearchScreen',
  NEW_CONNECTION_SCREEN: 'NewConnectionScreen',
  EDIT_PROFILE_SCREEN: 'EditProfileScreen',
  SETTINGS_SCREEN: 'SettingsScreen',
  PRIVACY_POLICY_SCREEN: 'PrivacyPolicyScreen',
  FORGOT_PASSWORD_SCREEN: 'ForgotPasswordScreen',
  UPDATE_PASSWORD_SCREEN: 'UpdatePasswordScreen',
} as const;
