export type IconVariant =
  | 'back'
  | 'close'
  | 'flipCamera'
  | 'flashOn'
  | 'flashOff'
  | 'home'
  | 'explore'
  | 'profile'
  | 'settings'
  | 'heart'
  | 'chevronDown'
  | 'image'
  | 'chevronRight'
  | 'logOut'
  | 'send'
  | 'download'
  | 'location'
  | 'warning'
  | 'globe'
  | 'userAdd'
  | 'userCheck'
  | 'search'
  | 'camera'
  | 'qr'
  | 'paperStack'
  | 'dots'
  | 'plus'
  | 'nfc'
  | 'qrCorners'
  | 'write'
  | 'userRemove'
  | 'chat'
  | 'share'
  | 'copy';

export type IconSize = 'small' | 'extraSmall' | 'medium' | 'large' | 'extraLarge' | number;
